# Generated by Django 3.0.5 on 2020-12-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categories_genres_titles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='slug',
        ),
    ]
