# Generated by Django 3.0.5 on 2020-12-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_titles_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
