# Generated by Django 3.0.5 on 2020-12-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_titles_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='description',
            field=models.TextField(default=None, max_length=2000),
        ),
    ]
