# Generated by Django 3.0.5 on 2020-12-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201213_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
