# Generated by Django 3.0.5 on 2020-12-13 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201213_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='description',
        ),
    ]
