# Generated by Django 3.0.5 on 2020-12-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_titles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
