# Generated by Django 3.0.5 on 2020-12-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20201213_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='rating',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
