# Generated by Django 3.0.5 on 2020-12-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201213_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titles',
            old_name='genres',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
