# Generated by Django 3.0.5 on 2020-12-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comments_reviews'),
        ('api', '0014_auto_20201213_1712'),
    ]

    operations = [
    ]
